databases:
  - name: za-support-db
    databaseName: za_support_db
    user: za_support
    plan: basic-1gb
    region: oregon

services:
  - type: web
    name: za-support-backend
    runtime: python
    pythonVersion: "3.11.7"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: ZAS_demo123
      - key: ENCRYPTION_KEY
        value: 8JuuBTgzmc59mtw1F-jbNh3Ke72QCrVnhTJH3IBPyUk=
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: za-support-db
          property: connectionString
