#!/bin/bash
# ZA SUPPORT — Chat Catalog & Consolidation Script
# Run on Courtney's Mac: bash scripts/catalog_chats.sh
# Scans all Claude Code chat sessions, extracts topics, and categorizes into 5 consolidated groups
# Date: 12/03/2026

set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
PROJECTS_DIR="$CLAUDE_DIR/projects"
OUTPUT_DIR="$HOME/Developer/za-support-backend/chat_consolidation"
CATALOG_FILE="$OUTPUT_DIR/chat_catalog.md"
CONTEXT_DIR="$OUTPUT_DIR/extracted_context"

mkdir -p "$OUTPUT_DIR" "$CONTEXT_DIR"

echo "═══════════════════════════════════════════════════════════"
echo "  ZA SUPPORT — Chat Catalog & Consolidation"
echo "  Scanning all Claude Code sessions..."
echo "═══════════════════════════════════════════════════════════"

# Initialize catalog
cat > "$CATALOG_FILE" <<'HEADER'
# ZA SUPPORT — Chat Catalog
# Auto-generated by catalog_chats.sh
# Date: $(date '+%d/%m/%Y %H:%M')

## Chat Categories

### CHAT 1: CRM, Sales & Client Management
Keywords: CRM, sales, client, Investec, upsell, warranty, pricing, segmentation, check-in, lifecycle, device age

### CHAT 2: Diagnostics, Scout & Monitoring
Keywords: Scout, diagnostic, ISP, outage, monitor, heartbeat, agent, telemetry, backup, patch, ESET, security, dedup

### CHAT 3: Reports, Assessments & Knowledge Base
Keywords: report, assessment, guide, medical, HPCSA, template, PDF, ReportLab, Flipper, photo, asset register

### CHAT 4: AI/ML, Agents & Automation
Keywords: AI, ML, profiling, research, agent registry, orchestrator, Claude API, embedding, pgvector, Graph API

### CHAT 5: Dashboard, Infrastructure & DevOps
Keywords: dashboard, Render, Vercel, deploy, migration, Redis, database, infrastructure, CORS, Docker, Playwright

---

## All Discovered Sessions

HEADER

# Category keyword arrays
CHAT1_KEYWORDS="crm|sales|client|investec|upsell|warranty|pricing|segment|check.in|lifecycle|device.age|opportunity|lead"
CHAT2_KEYWORDS="scout|diagnostic|isp|outage|monitor|heartbeat|agent|telemetry|backup|patch|eset|security|dedup|duplicate|cyber|network|connectivity"
CHAT3_KEYWORDS="report|assessment|guide|medical|hpcsa|template|pdf|reportlab|flipper|photo|asset.register|knowledge.base|customer.guide"
CHAT4_KEYWORDS="ai_profil|ml|profiling|research|agent.registry|orchestrat|claude.api|embedding|pgvector|graph.api|microsoft.graph|onedrive|automation.agent"
CHAT5_KEYWORDS="dashboard|render|vercel|deploy|migration|redis|database|infrastructure|cors|docker|playwright|devops|github|ci.cd|build"

# Counters
TOTAL=0
CAT1=0; CAT2=0; CAT3=0; CAT4=0; CAT5=0; UNCATEGORIZED=0

# Function to extract first user message and key context from a session file
extract_session_info() {
    local session_file="$1"
    local session_id
    session_id=$(basename "$session_file" .jsonl)

    # Get file modification date
    local mod_date
    mod_date=$(stat -f '%Sm' -t '%d/%m/%Y %H:%M' "$session_file" 2>/dev/null || stat --format='%y' "$session_file" 2>/dev/null | cut -d' ' -f1)

    # Get file size
    local file_size
    file_size=$(wc -c < "$session_file" | tr -d ' ')

    # Get message count (lines = messages)
    local msg_count
    msg_count=$(wc -l < "$session_file" | tr -d ' ')

    # Extract first user message (topic indicator)
    local first_msg
    first_msg=$(head -5 "$session_file" | grep -o '"content":"[^"]*"' | head -1 | sed 's/"content":"//;s/"$//' | cut -c1-200 2>/dev/null || echo "Unable to parse")

    # Extract all unique content snippets for keyword matching
    local all_content
    all_content=$(grep -oE '"content":"[^"]{0,500}"' "$session_file" | head -50 | tr '[:upper:]' '[:lower:]' 2>/dev/null || echo "")

    # Categorize based on keywords
    local category="UNCATEGORIZED"
    local cat1_hits cat2_hits cat3_hits cat4_hits cat5_hits
    cat1_hits=$(echo "$all_content" | grep -cEi "$CHAT1_KEYWORDS" 2>/dev/null || echo 0)
    cat2_hits=$(echo "$all_content" | grep -cEi "$CHAT2_KEYWORDS" 2>/dev/null || echo 0)
    cat3_hits=$(echo "$all_content" | grep -cEi "$CHAT3_KEYWORDS" 2>/dev/null || echo 0)
    cat4_hits=$(echo "$all_content" | grep -cEi "$CHAT4_KEYWORDS" 2>/dev/null || echo 0)
    cat5_hits=$(echo "$all_content" | grep -cEi "$CHAT5_KEYWORDS" 2>/dev/null || echo 0)

    # Find max hits
    local max_hits=0
    for h in $cat1_hits $cat2_hits $cat3_hits $cat4_hits $cat5_hits; do
        if [ "$h" -gt "$max_hits" ]; then
            max_hits=$h
        fi
    done

    if [ "$max_hits" -gt 0 ]; then
        if [ "$cat1_hits" -eq "$max_hits" ]; then category="CHAT 1: CRM/Sales"; ((CAT1++)) || true
        elif [ "$cat2_hits" -eq "$max_hits" ]; then category="CHAT 2: Diagnostics"; ((CAT2++)) || true
        elif [ "$cat3_hits" -eq "$max_hits" ]; then category="CHAT 3: Reports"; ((CAT3++)) || true
        elif [ "$cat4_hits" -eq "$max_hits" ]; then category="CHAT 4: AI/Agents"; ((CAT4++)) || true
        elif [ "$cat5_hits" -eq "$max_hits" ]; then category="CHAT 5: Infra"; ((CAT5++)) || true
        fi
    else
        ((UNCATEGORIZED++)) || true
    fi

    # Write to catalog
    cat >> "$CATALOG_FILE" <<SESSION_ENTRY
### Session: $session_id
- **Category:** $category
- **Last Modified:** $mod_date
- **Size:** $file_size bytes | **Messages:** $msg_count
- **Keyword Hits:** CRM=$cat1_hits | Diag=$cat2_hits | Reports=$cat3_hits | AI=$cat4_hits | Infra=$cat5_hits
- **First Message:** $first_msg

SESSION_ENTRY

    # Extract key decisions and context to per-category files
    local context_file="$CONTEXT_DIR/${category// /_}.md"
    echo "## From session: $session_id ($mod_date)" >> "$context_file"
    echo "" >> "$context_file"

    # Extract lines containing key decision indicators
    grep -oE '"content":"[^"]{0,1000}"' "$session_file" 2>/dev/null | \
        grep -iE "decision|implement|created|built|changed|fixed|added|removed|migrated|deployed|configured|updated|resolved" | \
        head -20 | \
        sed 's/"content":"//;s/"$//' >> "$context_file" 2>/dev/null || true
    echo "" >> "$context_file"
    echo "---" >> "$context_file"
    echo "" >> "$context_file"

    ((TOTAL++)) || true
}

# Scan all project directories for session files
echo ""
echo "Scanning $PROJECTS_DIR..."

if [ -d "$PROJECTS_DIR" ]; then
    # Find all .jsonl session files
    find "$PROJECTS_DIR" -name "*.jsonl" -type f | sort -t/ -k$(echo "$PROJECTS_DIR" | tr -cd '/' | wc -c | tr -d ' ') | while read -r session_file; do
        echo "  Processing: $(basename "$session_file" .jsonl)"
        extract_session_info "$session_file"
    done
else
    echo "WARNING: $PROJECTS_DIR does not exist. Are you running this on Courtney's Mac?"
    exit 1
fi

# Also check for sessions in the main claude directory
if [ -d "$CLAUDE_DIR" ]; then
    find "$CLAUDE_DIR" -maxdepth 2 -name "*.jsonl" -type f ! -path "*/projects/*" | while read -r session_file; do
        echo "  Processing (root): $(basename "$session_file" .jsonl)"
        extract_session_info "$session_file"
    done
fi

# Write summary
cat >> "$CATALOG_FILE" <<SUMMARY

---

## SUMMARY

| Category | Count |
|----------|-------|
| Chat 1: CRM/Sales | $CAT1 |
| Chat 2: Diagnostics | $CAT2 |
| Chat 3: Reports | $CAT3 |
| Chat 4: AI/Agents | $CAT4 |
| Chat 5: Infra | $CAT5 |
| Uncategorized | $UNCATEGORIZED |
| **Total** | **$TOTAL** |

## NEXT STEPS

1. Review uncategorized sessions and manually assign them
2. Review extracted context files in: $CONTEXT_DIR/
3. Open each context file and merge key decisions into the session MEMORY files
4. Start 5 new Claude Code sessions with the consolidated context

## OUTPUT FILES
- Catalog: $CATALOG_FILE
- Extracted context per category: $CONTEXT_DIR/
SUMMARY

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  COMPLETE: Cataloged $TOTAL sessions"
echo "  Chat 1 (CRM): $CAT1 | Chat 2 (Diag): $CAT2 | Chat 3 (Reports): $CAT3"
echo "  Chat 4 (AI): $CAT4 | Chat 5 (Infra): $CAT5 | Uncategorized: $UNCATEGORIZED"
echo ""
echo "  Catalog: $CATALOG_FILE"
echo "  Context: $CONTEXT_DIR/"
echo "═══════════════════════════════════════════════════════════"

# macOS notification
osascript -e 'display notification "Chat catalog complete — check chat_consolidation/" with title "ZA Support" sound name "Glass"' 2>/dev/null || true
